{% set version = "3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmap/tmap_{{ version }}.tar.gz
  sha256: e3b15a7f18bbcf8ab2ed4e381cf39c385fbfb364e6c93c4e4e6cc360739ba875

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-classint
    - r-htmltools
    - r-htmlwidgets
    - r-leaflet >=2.0.2
    - r-leafsync
    - r-lwgeom >=0.1_4
    - r-raster >=2.7_15
    - r-sf >=0.7_1
    - r-tmaptools >=2.0_2
    - r-units >=0.6_1
    - r-viridislite
  run:
    - r-base
    - r-rcolorbrewer
    - r-classint
    - r-htmltools
    - r-htmlwidgets
    - r-leaflet >=2.0.2
    - r-leafsync
    - r-lwgeom >=0.1_4
    - r-raster >=2.7_15
    - r-sf >=0.7_1
    - r-tmaptools >=2.0_2
    - r-units >=0.6_1
    - r-viridislite

test:
  commands:
    - $R -e "library('tmap')"           # [not win]
    - "\"%R%\" -e \"library('tmap')\""  # [win]

about:
  home: https://github.com/mtennekes/tmap
  license: GPL-3
  summary: Thematic maps are geographical maps in which spatial data distributions are visualized. This package offers a flexible, layer-based, and easy to use approach
    to create thematic maps, such as choropleths and bubble maps.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  description: Set of tools for reading and processing spatial data. The aim is to supply the workflow to create thematic maps. This package also facilitates 'tmap',
    the package for visualizing thematic maps.
  doc_url: https://cran.r-project.org/web/packages/tmap/tmap.pdf
  dev_url: https://github.com/mtennekes/tmap

extra:
  recipe-maintainers:
    - conda-forge/r
    - agcopenhaver
    - oblute
    - tata17

# Package: tmap
# License: GPL-3
# Title: Thematic Maps
# Type: Package
# LazyLoad: yes
# Authors@R: c( person("Martijn", "Tennekes", email = "mtennekes@gmail.com", role = c("aut", "cre")), person("Joel", "Gombin", email = "joel.gombin@gmail.com", role = "ctb"), person("Sebastian", "Jeworutzki", email = "Sebastian.Jeworutzki@rub.de", role = "ctb"), person("Kent", "Russell", email = "kent.russell@timelyportfolio.com", role = "ctb"), person("Richard", "Zijdeman", email = "richard.zijdeman@iisg.nl", role = "ctb"), person("John", "Clouse", email = "johnaclouse@gmail.com", role = "ctb"), person("Robin", "Lovelace", email = "rob00x@gmail.com", role = "ctb"), person("Jakub", "Nowosad", email = "nowosad.jakub@gmail.com", role = "ctb"), person("Jannes", "Muenchow", email = "jannes.muenchow@uni-jena.de", role = "ctb") )
# Description: Thematic maps are geographical maps in which spatial data distributions are visualized. This package offers a flexible, layer-based, and easy to use approach to create thematic maps, such as choropleths and bubble maps.
# Version: 2.3-1
# Date: 2019-09-17
# Depends: R (>= 3.0), methods
# Imports: tmaptools (>= 2.0-2), sf (>= 0.7-1), lwgeom (>= 0.1-4), units (>= 0.6-1), raster (>= 2.7-15), grid, RColorBrewer, viridisLite, classInt, htmltools, htmlwidgets, leaflet (>= 2.0.2), leafsync, stats
# Suggests: rmapshaper, rmarkdown, knitr, png, cartogram, osmdata, ggplot2, dplyr, tidyr, shiny, testthat, covr
# URL: https://github.com/mtennekes/tmap
# BugReports: https://github.com/mtennekes/tmap/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-17 08:58:50 UTC; mtes
# Author: Martijn Tennekes [aut, cre], Joel Gombin [ctb], Sebastian Jeworutzki [ctb], Kent Russell [ctb], Richard Zijdeman [ctb], John Clouse [ctb], Robin Lovelace [ctb], Jakub Nowosad [ctb], Jannes Muenchow [ctb]
# Maintainer: Martijn Tennekes <mtennekes@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-17 09:40:02 UTC
